<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache.maven</groupId>
    <artifactId>maven-parent</artifactId>
    <version>47</version>
    <relativePath />
  </parent>
  <groupId>org.apache.maven.executor</groupId>
  <artifactId>executor</artifactId>
  <version>1.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Apache Maven Executor</name>
  <description>Executor is a Maven execution framework.</description>
  <url>https://maven.apache.org/executor/</url>
  <inceptionYear>2026</inceptionYear>

  <modules>
    <module>test-utilities</module>
    <module>maven-executor</module>
    <module>providers</module>
  </modules>

  <scm>
    <connection>scm:git:https://gitbox.apache.org/repos/asf/maven-executor.git</connection>
    <developerConnection>scm:git:https://gitbox.apache.org/repos/asf/maven-executor.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/apache/maven-executor/tree/${project.scm.tag}</url>
  </scm>
  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/apache/maven-executor/issues</url>
  </issueManagement>
  <ciManagement>
    <system>Jenkins</system>
    <url>https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-executor/</url>
  </ciManagement>
  <distributionManagement>
    <site>
      <id>apache.website</id>
      <url>scm:svn:https://svn.apache.org/repos/asf/maven/website/components/${maven.site.path}</url>
    </site>
  </distributionManagement>

  <properties>
    <javaVersion>17</javaVersion>
    <maven.site.path>executor-archives/executor-LATEST</maven.site.path>
    <project.build.outputTimestamp>2026-04-30T20:37:18Z</project.build.outputTimestamp>
    <testTmpDir>${project.build.directory}/tmp</testTmpDir>

    <version.maven3>3.9.15</version.maven3>
    <version.maven3resolver>1.9.27</version.maven3resolver>
    <version.maven4>4.0.0-rc-5</version.maven4>

    <version.slf4j>2.0.17</version.slf4j>
    <versions.junit5>6.0.3</versions.junit5>
    <version.mockito>5.23.0</version.mockito>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- project dependencies -->
      <dependency>
        <groupId>org.apache.maven.executor</groupId>
        <artifactId>test-utilities</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.maven.executor</groupId>
        <artifactId>maven-executor</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- Testcontainers -->
      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers</artifactId>
        <version>2.0.5</version>
      </dependency>

      <!-- other dependencies -->
      <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>1.22.0</version>
      </dependency>
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.22.0</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${version.slf4j}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>${version.slf4j}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <configuration>
            <topSiteURL>scm:svn:https://svn.apache.org/repos/asf/maven/website/components/${maven.site.path}</topSiteURL>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <useModulePath>false</useModulePath>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>Jenkinsfile</exclude>
            <exclude>.github/**</exclude>
            <exclude>deploySite.bat</exclude>
            <exclude>deploySite.sh</exclude>
            <exclude>LICENCE</exclude>
            <exclude>NOTICE</exclude>
            <exclude>LICENCE</exclude>
            <!--
              ! Excluded the license files itself cause they do not have a license of themselves.
            -->
            <exclude>src/main/appended-resources/licenses/**</exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <!-- This is just an empty profile to not fail Maven 4 build that uses -P run-its -->
      <id>run-its</id>
    </profile>
  </profiles>
</project>
